### ISSUE TITLE
Chiltepec Chinantec text contains what I’m pretty sure is not a letter

### ISSUE THREAD

**Issue by berrymot** [unicode-org/udhr#40]
![A8B3B7A4-2EA7-400C-9D60-44ABD8AD6D69](https://user-images.githubusercontent.com/50974538/142088703-2d8955c6-cb64-4439-80cc-983949012191.jpeg)

See that? `Lej†̎`? Why is that there? What is a *dagger with two vertical lines* doing in a UDHR translation?

My best guess is it might be a (poor) substitute for a barred i with dieresis but I have little evidence to back that up.

**Comment by eric-muller** [comment]
Yes, it's pretty obvious that there is an error. However, nobody seems to know what it should be, only a guess. I think it's better to have something obviously wrong rather than something plausible but wrong. The error is noted in the status&history page (https://github.com/unicode-org/udhr/blob/master/data/status/status_csa.xml, https://unicode.org/udhr/s/status_csa.html)
