### ISSUE TITLE
We cannot spread  Universal Declaration of Human Rights

### ISSUE THREAD

**Issue by Pantyhose-X** [unicode-org/udhr#44]
No open source license Universal Declaration of Human Rights
I wanted to use the project for https://content.minetest.net/threads/3092/ but it was rejected

**Comment by eric-muller** [comment]
For the English and the French versions, the only plausible copyright holder is the United Nations, and so they are the only ones who can either assert they have no copyright, or provide reproduction rights. Please ask them if you need that.

That being said, it would make absolutely no sense for the United Nations to make the reproduction of the UDHR difficult in any way. The OHCHR has been aware of the UDHR in Unicode project since 2005, and has never raised any objection.

**Comment by eric-muller** [comment]
You may also want to look at <https://documents-dds-ny.un.org/doc/RESOLUTION/GEN/NR0/043/88/PDF/NR004388.pdf?OpenElement>, which is the record of the resolution adopting the UDHR. Part A is the declaration itself, part D (on page 78) is "Publicity to be given to the Universal Declaration of Human Rights". Seems that this should cover your needs.
